[project]
name = "massless"
description = "Reinout's scripts for lowering his mass and making nice graphs"
authors = [
    {name = "Reinout van Rees", email = "reinout@vanrees.org"},
]
readme = "README.md"
license = {text = "MIT"}
# Get classifier strings from http://www.python.org/pypi?%3Aaction=list_classifiers
classifiers = ["Programming Language :: Python"]
keywords = []
requires-python = ">=3.7"
dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "typer[all]",
    "xmltodict",
]
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "data-science-types",
    "pytest",
    "pytest-cov",
    "pytest-mypy",
    "types-xmltodict"
]

[project.urls]
homepage = "https://github.com/nens/massless"

[project.scripts]
run-massless = "massless.scripts:main"

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
include = ["massless*"]
# package names should match these glob patterns (["*"] by default)

[tool.setuptools.dynamic]
version = {attr = "massless.__version__"}

[tool.isort]
profile = "black"
force_alphabetical_sort_within_sections = true
force_single_line = true

[tool.pytest.ini_options]
norecursedirs=".venv data doc etc *.egg-info misc var build lib include"
python_files = "test_*.py"
testpaths = "massless"
